# vim ft=yaml
language: python
python:
  - 3.6
  - 3.7
  - 3.8
  - 3.9

cache:
  - apt

env:
  global:
    # will be used in the matrix, where neither other variable is used
    - BOTO_CONFIG=/tmp/nowhere
    - DATALAD_TESTS_SSH=1

before_install:
  # The ultimate one-liner setup for NeuroDebian repository
  - bash <(wget -q -O- http://neuro.debian.net/_files/neurodebian-travis.sh)
  - travis_retry sudo apt-get update -qq
  - travis_retry sudo apt-get install git-annex-standalone dcm2niix
  # Install in our own virtualenv
  - python -m pip install --upgrade pip
  - pip install --upgrade virtualenv
  - virtualenv --python=python venv
  - source venv/bin/activate
  - pip --version # check again since seems that python_requires='>=3.5' in secretstorage is not in effect
  - python --version # just to check
  - pip install -r dev-requirements.txt
  - pip install requests # below installs pyld but that assumes we have requests already
  - pip install datalad
  - pip install codecov pytest

install:
  - git config --global user.email "test@travis.land"
  - git config --global user.name "Travis Almighty"

script:
  - coverage run `which py.test` -s -v heudiconv

after_success:
  - codecov
